// Copyright 2026 The Open Brush Authors
// Licensed under the Apache License, Version 2.0.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace TiltBrush
{
    // Native reader for the v0.1.1 keyboard/mouse mapping file. The failure codes must agree with
    // the C:\Dev\chris reference validator (src/chris/core/mapping.py) on every case in schemas/v0.1.1/fixtures/cases.json
    // (generated by src/chris/core/mapping_cases.py);
    // message text may differ. Plain classes so batchmode editor checks can cover them.
    public sealed class CHRISMappingException : Exception
    {
        public string Code { get; }
        public string Detail { get; }
        public CHRISMappingException(string code, string detail) : base(code + ": " + detail)
        {
            Code = code;
            Detail = detail;
        }
    }

    public enum CHRISMappedAction {
        Draw, Undo, MoveBrush, MoveView, BrushSize,
        Trigger, GripToggle, PrimaryButton, SecondaryButton, StickClick, StickAxis,
        PoseXY, PoseDepth, RotateXY, RotateRoll, SelectHand, ModeUI, ModePosition,
        ModeRotation, Recenter, HandBack
    }
    public enum CHRISMappingSource { Key, MouseButton, KeyVector2, MouseDelta, MouseWheel, KeyAxis1 }

    public sealed class CHRISInputMappingEntry
    {
        public string Id { get; internal set; }
        public CHRISMappedAction Action { get; internal set; }
        public CHRISMappingSource Source { get; internal set; }
        // Key: Key. MouseButton: Button ("left", "right", "middle"). KeyVector2: Up/Down/Left/Right.
        public string Key { get; internal set; }
        public string Button { get; internal set; }
        public string Up { get; internal set; }
        public string Down { get; internal set; }
        public string Left { get; internal set; }
        public string Right { get; internal set; }
        public string Negative { get; internal set; }
        public string Positive { get; internal set; }
        public string Target { get; internal set; }
    }

    public sealed class CHRISInputMapping
    {
        public const int MaxBytes = 16384;
        public const string Version = "v0.1.1";
        public const string BimanualVersion = "v0.1.2";
        public const string DirectPoseVersion = "v0.1.3";

        public IReadOnlyList<CHRISInputMappingEntry> Mappings { get; }
        public string SchemaVersion { get; }
        public bool IsBimanual => SchemaVersion == BimanualVersion || SchemaVersion == DirectPoseVersion;
        CHRISInputMapping(List<CHRISInputMappingEntry> mappings, string version = Version)
        {
            Mappings = mappings.AsReadOnly();
            SchemaVersion = version;
        }

        public CHRISInputMappingEntry Find(CHRISMappedAction action)
        {
            foreach (var mapping in Mappings)
                if (mapping.Action == action) return mapping;
            return null;
        }

        public CHRISInputMappingEntry Find(CHRISMappedAction action, string target)
        {
            foreach (var mapping in Mappings)
                if (mapping.Action == action && mapping.Target == target) return mapping;
            return null;
        }

        static readonly HashSet<string> Keys = new HashSet<string>(StringComparer.Ordinal)
        {
            "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
            "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
            "space", "enter", "tab", "backspace",
            "upArrow", "downArrow", "leftArrow", "rightArrow",
        };
        static readonly HashSet<string> BimanualKeys = new HashSet<string>(Keys, StringComparer.Ordinal) {
            "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12"
        };
        static readonly string[] VectorSides = { "up", "down", "left", "right" };

        public static CHRISInputMapping Load(string path) => Parse(ReadBounded(path));

        // Reads at most one byte past the limit so an oversized file is never loaded whole.
        internal static byte[] ReadBounded(string path)
        {
            using (var stream = File.OpenRead(path))
            {
                var buffer = new byte[MaxBytes + 1];
                int total = 0, read;
                while (total < buffer.Length && (read = stream.Read(buffer, total, buffer.Length - total)) > 0)
                    total += read;
                if (total > MaxBytes)
                    throw new CHRISMappingException("too_large", $"more than {MaxBytes} bytes");
                Array.Resize(ref buffer, total);
                return buffer;
            }
        }

        public static CHRISInputMapping Parse(byte[] raw)
        {
            if (raw.Length > MaxBytes)
                throw new CHRISMappingException("too_large", $"{raw.Length} bytes exceeds {MaxBytes}");
            int start = raw.Length >= 3 && raw[0] == 0xEF && raw[1] == 0xBB && raw[2] == 0xBF ? 3 : 0;
            string text;
            try { text = new UTF8Encoding(false, true).GetString(raw, start, raw.Length - start); }
            catch (DecoderFallbackException error) { throw new CHRISMappingException("invalid_json", error.Message); }
            var document = new StrictJson(text).ParseDocument();
            if (document is Dictionary<string, object> root &&
                root.TryGetValue("version", out var version) && version is string named &&
                (named == BimanualVersion || named == DirectPoseVersion)) return CheckBimanual(root, named);
            return Check(document);
        }

        static CHRISMappingException Schema(string where, string detail) =>
            new CHRISMappingException("schema", (where.Length == 0 ? "(root)" : where) + ": " + detail);

        static CHRISInputMapping Check(object document)
        {
            if (!(document is Dictionary<string, object> root)) throw Schema("", "must be an object");
            foreach (var name in root.Keys)
                if (name != "version" && name != "app" && name != "profile" && name != "mappings")
                    throw Schema("", $"unknown field '{name}'");
            Const(root, "version", Version, "");
            Const(root, "app", "openbrush", "");
            Const(root, "profile", "keyboard_mouse", "");
            if (!root.TryGetValue("mappings", out var listValue)) throw Schema("", "'mappings' is required");
            if (!(listValue is List<object> list)) throw Schema("mappings", "must be an array");
            if (list.Count == 0) throw Schema("mappings", "must not be empty");

            var entries = new List<CHRISInputMappingEntry>();
            for (int i = 0; i < list.Count; i++) entries.Add(Entry(list[i], "mappings/" + i));
            int draws = 0;
            foreach (var entry in entries) if (entry.Action == CHRISMappedAction.Draw) draws++;
            if (draws != 1) throw Schema("mappings", "exactly one draw mapping is required");

            // Same order as the reference: per mapping, id then inputs then action.
            var ids = new Dictionary<string, string>(StringComparer.Ordinal);
            var inputs = new Dictionary<string, string>(StringComparer.Ordinal);
            var actions = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var entry in entries)
            {
                Unique("duplicate_id", ids, entry.Id, entry.Id);
                foreach (var input in Inputs(entry)) Unique("duplicate_input", inputs, input, entry.Id);
                Unique("duplicate_action", actions, ActionName(entry.Action), entry.Id);
            }
            return new CHRISInputMapping(entries);
        }

        static CHRISInputMapping CheckBimanual(Dictionary<string, object> root, string version)
        {
            OnlyFields(root, "", "version", "app", "profile", "frame", "mappings");
            Const(root, "version", version, "");
            Const(root, "app", "openbrush", "");
            Const(root, "profile", "keyboard_mouse", "");
            if (!(root["frame"] is Dictionary<string, object> frame)) throw Schema("frame", "must be an object");
            OnlyFields(frame, "frame", "kind");
            Const(frame, "kind", "fixed_recenterable", "frame");
            if (!(root["mappings"] is List<object> list) || list.Count == 0 || list.Count > 64)
                throw Schema("mappings", "must have 1 to 64 entries");

            // Validate every row's shape before checking cross-row claims, as the shared schema does.
            var entries = new List<CHRISInputMappingEntry>();
            for (int i = 0; i < list.Count; i++)
            {
                var entry = BimanualEntry(list[i], "mappings/" + i);
                if (version == DirectPoseVersion && entry.Action == CHRISMappedAction.ModeRotation)
                    throw Schema("mappings/" + i + "/action", "v0.1.3 uses combined pose control");
                entries.Add(entry);
            }
            var ids = new Dictionary<string, string>(StringComparer.Ordinal);
            var actions = new Dictionary<string, string>(StringComparer.Ordinal);
            var claims = new Dictionary<string, List<KeyValuePair<int, string>>>(StringComparer.Ordinal);
            for (int i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                Unique("duplicate_id", ids, entry.Id, entry.Id);
                int scope = InputScope(entry.Action);
                if (version == DirectPoseVersion && (scope == 2 || scope == 4)) scope = 6;
                foreach (string input in Inputs(entry))
                {
                    if (!claims.TryGetValue(input, out var previous)) claims[input] = previous = new List<KeyValuePair<int, string>>();
                    foreach (var claim in previous)
                        if ((claim.Key & scope) != 0)
                            throw new CHRISMappingException("duplicate_input", $"'{input}' in '{entry.Id}' and '{claim.Value}'");
                    previous.Add(new KeyValuePair<int, string>(scope, entry.Id));
                }
                Unique("duplicate_action", actions, ActionName(entry.Action) + ":" + entry.Target, entry.Id);
            }
            foreach (var required in BimanualRequired)
            {
                if (version == DirectPoseVersion && (required == "mode_rotation:" || required == "rotate_roll:selected"))
                    continue;
                if (!actions.ContainsKey(required))
                    throw Schema("mappings", "required " + required + " is missing");
            }
            return new CHRISInputMapping(entries, version);
        }

        static readonly string[] BimanualRequired = {
            "mode_ui:", "mode_position:", "mode_rotation:", "select_hand:brush", "select_hand:wand",
            "recenter:", "hand_back:", "pose_xy:selected", "pose_depth:selected",
            "rotate_xy:selected", "rotate_roll:selected", "trigger:brush", "trigger:wand",
            "grip_toggle:brush", "grip_toggle:wand"
        };

        // UI, position and rotation are disjoint scopes; global commands overlap all of them.
        static int InputScope(CHRISMappedAction action)
        {
            switch (action)
            {
                case CHRISMappedAction.PoseXY:
                case CHRISMappedAction.PoseDepth: return 2;
                case CHRISMappedAction.RotateXY:
                case CHRISMappedAction.RotateRoll: return 4;
                case CHRISMappedAction.Trigger:
                case CHRISMappedAction.GripToggle:
                case CHRISMappedAction.PrimaryButton:
                case CHRISMappedAction.SecondaryButton:
                case CHRISMappedAction.StickClick:
                case CHRISMappedAction.StickAxis:
                case CHRISMappedAction.Undo:
                case CHRISMappedAction.BrushSize:
                case CHRISMappedAction.MoveView: return 6;
                default: return 7;
            }
        }

        static string BimanualKeyName(Dictionary<string, object> source, string name, string at)
        {
            if (!(source[name] is string key) || !BimanualKeys.Contains(key))
                throw Schema(at + "/" + name, "not an allowed key name");
            return key;
        }

        static CHRISInputMappingEntry BimanualEntry(object value, string where)
        {
            if (!(value is Dictionary<string, object> obj)) throw Schema(where, "must be an object");
            bool hasTarget = obj.ContainsKey("target");
            OnlyFields(obj, where, hasTarget ? new[] { "id", "source", "action", "target" } :
                new[] { "id", "source", "action" });
            if (!(obj["id"] is string id) || !ValidId(id)) throw Schema(where + "/id", "must match ^[a-z][a-z0-9_]*$");
            if (!(obj["action"] is string actionName) || !BimanualActions.TryGetValue(actionName, out var action))
                throw Schema(where + "/action", "unknown action");
            var entry = new CHRISInputMappingEntry { Id = id, Action = action };
            string target = hasTarget ? obj["target"] as string : null;
            bool hand = action == CHRISMappedAction.Trigger || action == CHRISMappedAction.GripToggle ||
                action == CHRISMappedAction.PrimaryButton || action == CHRISMappedAction.SecondaryButton ||
                action == CHRISMappedAction.StickClick || action == CHRISMappedAction.StickAxis ||
                action == CHRISMappedAction.SelectHand;
            bool pose = action == CHRISMappedAction.PoseXY || action == CHRISMappedAction.PoseDepth ||
                action == CHRISMappedAction.RotateXY || action == CHRISMappedAction.RotateRoll;
            if (hand && target != "brush" && target != "wand") throw Schema(where + "/target", "must be brush or wand");
            if (pose && target != "selected") throw Schema(where + "/target", "must be selected");
            if (!hand && !pose && hasTarget) throw Schema(where + "/target", "not allowed for this action");
            entry.Target = target;

            string at = where + "/source";
            if (!(obj["source"] is Dictionary<string, object> source)) throw Schema(at, "must be an object");
            string type = source.TryGetValue("type", out var t) ? t as string : null;
            bool button = hand && action != CHRISMappedAction.StickAxis && action != CHRISMappedAction.SelectHand ||
                action == CHRISMappedAction.Undo;
            bool global = action == CHRISMappedAction.ModeUI || action == CHRISMappedAction.ModePosition ||
                action == CHRISMappedAction.ModeRotation || action == CHRISMappedAction.Recenter ||
                action == CHRISMappedAction.HandBack || action == CHRISMappedAction.SelectHand;
            bool vector = action == CHRISMappedAction.StickAxis || action == CHRISMappedAction.PoseXY ||
                action == CHRISMappedAction.RotateXY || action == CHRISMappedAction.MoveView;
            bool scalar = action == CHRISMappedAction.PoseDepth || action == CHRISMappedAction.RotateRoll;
            if ((button || global) && type == "key")
            {
                OnlyFields(source, at, "type", "key");
                entry.Source = CHRISMappingSource.Key;
                if (action == CHRISMappedAction.ModeUI)
                {
                    if (!(source["key"] is string recovery) || recovery != "f1")
                        throw Schema(at + "/key", "mode_ui must use F1 for recovery");
                    entry.Key = recovery;
                }
                else entry.Key = BimanualKeyName(source, "key", at);
                if (global && (entry.Key == "enter" || entry.Key == "upArrow" ||
                    entry.Key == "downArrow" || entry.Key == "leftArrow" || entry.Key == "rightArrow"))
                    throw Schema(at + "/key", "reserved for headset UI navigation");
            }
            else if (button && type == "mouse_button")
            {
                OnlyFields(source, at, "type", "button");
                string name = source["button"] as string;
                if (name != "left" && name != "right" && name != "middle") throw Schema(at + "/button", "must be left, right or middle");
                entry.Source = CHRISMappingSource.MouseButton;
                entry.Button = name;
            }
            else if (vector && type == "key_vector2")
            {
                OnlyFields(source, at, "type", "up", "down", "left", "right");
                entry.Source = CHRISMappingSource.KeyVector2;
                entry.Up = BimanualKeyName(source, "up", at);
                entry.Down = BimanualKeyName(source, "down", at);
                entry.Left = BimanualKeyName(source, "left", at);
                entry.Right = BimanualKeyName(source, "right", at);
            }
            else if (vector && action != CHRISMappedAction.StickAxis && type == "mouse_delta")
            {
                OnlyFields(source, at, "type");
                entry.Source = CHRISMappingSource.MouseDelta;
            }
            else if (scalar && type == "key_axis1")
            {
                OnlyFields(source, at, "type", "negative", "positive");
                entry.Source = CHRISMappingSource.KeyAxis1;
                entry.Negative = BimanualKeyName(source, "negative", at);
                entry.Positive = BimanualKeyName(source, "positive", at);
            }
            else if ((scalar || action == CHRISMappedAction.BrushSize) && type == "mouse_wheel")
            {
                OnlyFields(source, at, "type");
                entry.Source = CHRISMappingSource.MouseWheel;
            }
            else throw Schema(at, "no allowed source for this action");
            return entry;
        }

        static readonly Dictionary<string, CHRISMappedAction> BimanualActions =
            new Dictionary<string, CHRISMappedAction>(StringComparer.Ordinal) {
                { "trigger", CHRISMappedAction.Trigger }, { "grip_toggle", CHRISMappedAction.GripToggle },
                { "primary_button", CHRISMappedAction.PrimaryButton }, { "secondary_button", CHRISMappedAction.SecondaryButton },
                { "stick_click", CHRISMappedAction.StickClick }, { "stick_axis", CHRISMappedAction.StickAxis },
                { "pose_xy", CHRISMappedAction.PoseXY }, { "pose_depth", CHRISMappedAction.PoseDepth },
                { "rotate_xy", CHRISMappedAction.RotateXY }, { "rotate_roll", CHRISMappedAction.RotateRoll },
                { "select_hand", CHRISMappedAction.SelectHand }, { "mode_ui", CHRISMappedAction.ModeUI },
                { "mode_position", CHRISMappedAction.ModePosition }, { "mode_rotation", CHRISMappedAction.ModeRotation },
                { "recenter", CHRISMappedAction.Recenter }, { "hand_back", CHRISMappedAction.HandBack },
                { "undo", CHRISMappedAction.Undo }, { "brush_size", CHRISMappedAction.BrushSize },
                { "move_view", CHRISMappedAction.MoveView }
            };

        static void Unique(string code, Dictionary<string, string> seen, string value, string id)
        {
            if (seen.TryGetValue(value, out var first))
                throw new CHRISMappingException(code, $"'{value}' in '{id}' and '{first}'");
            seen[value] = id;
        }

        // The physical inputs an entry claims, named as in the reference validator.
        public static IEnumerable<string> Inputs(CHRISInputMappingEntry entry)
        {
            switch (entry.Source)
            {
                case CHRISMappingSource.Key: return new[] { "key." + entry.Key };
                case CHRISMappingSource.KeyVector2:
                    return new[] { "key." + entry.Up, "key." + entry.Down, "key." + entry.Left, "key." + entry.Right };
                case CHRISMappingSource.MouseButton: return new[] { "mouse." + entry.Button };
                case CHRISMappingSource.MouseDelta: return new[] { "mouse.delta" };
                case CHRISMappingSource.KeyAxis1:
                    return new[] { "key." + entry.Negative, "key." + entry.Positive };
                default: return new[] { "mouse.wheel" };
            }
        }

        static string ActionName(CHRISMappedAction action)
        {
            foreach (var name in BimanualActions)
                if (name.Value == action) return name.Key;
            switch (action)
            {
                case CHRISMappedAction.Draw: return "draw";
                case CHRISMappedAction.Undo: return "undo";
                case CHRISMappedAction.MoveBrush: return "move_brush";
                case CHRISMappedAction.MoveView: return "move_view";
                default: return "brush_size";
            }
        }

        static void Const(Dictionary<string, object> obj, string name, string expected, string where)
        {
            string at = where.Length == 0 ? name : where + "/" + name;
            if (!obj.TryGetValue(name, out var value)) throw Schema(where, $"'{name}' is required");
            if (!(value is string text) || text != expected) throw Schema(at, $"must be '{expected}'");
        }

        static void OnlyFields(Dictionary<string, object> obj, string where, params string[] allowed)
        {
            foreach (var name in obj.Keys)
                if (Array.IndexOf(allowed, name) < 0) throw Schema(where, $"unknown field '{name}'");
            foreach (var name in allowed)
                if (!obj.ContainsKey(name)) throw Schema(where, $"'{name}' is required");
        }

        static string KeyName(Dictionary<string, object> obj, string name, string where)
        {
            if (!(obj[name] is string key) || !Keys.Contains(key))
                throw Schema(where + "/" + name, "not an allowed key name");
            return key;
        }

        static bool ValidId(string id)
        {
            if (id.Length == 0 || id[0] < 'a' || id[0] > 'z') return false;
            foreach (char c in id)
                if (!(c >= 'a' && c <= 'z') && !(c >= '0' && c <= '9') && c != '_') return false;
            return true;
        }

        static CHRISInputMappingEntry Entry(object value, string where)
        {
            if (!(value is Dictionary<string, object> obj)) throw Schema(where, "must be an object");
            OnlyFields(obj, where, "id", "source", "action");
            if (!(obj["id"] is string id) || !ValidId(id)) throw Schema(where + "/id", "must match ^[a-z][a-z0-9_]*$");
            var entry = new CHRISInputMappingEntry { Id = id };
            switch (obj["action"] as string)
            {
                case "draw": entry.Action = CHRISMappedAction.Draw; break;
                case "undo": entry.Action = CHRISMappedAction.Undo; break;
                case "move_brush": entry.Action = CHRISMappedAction.MoveBrush; break;
                case "move_view": entry.Action = CHRISMappedAction.MoveView; break;
                case "brush_size": entry.Action = CHRISMappedAction.BrushSize; break;
                default: throw Schema(where + "/action", "unknown action");
            }

            string at = where + "/source";
            if (!(obj["source"] is Dictionary<string, object> source)) throw Schema(at, "must be an object");
            string type = source.TryGetValue("type", out var t) ? t as string : null;
            bool button = entry.Action == CHRISMappedAction.Draw || entry.Action == CHRISMappedAction.Undo;
            bool vector = entry.Action == CHRISMappedAction.MoveBrush || entry.Action == CHRISMappedAction.MoveView;
            if (button && type == "key")
            {
                OnlyFields(source, at, "type", "key");
                entry.Source = CHRISMappingSource.Key;
                entry.Key = KeyName(source, "key", at);
            }
            else if (button && type == "mouse_button")
            {
                OnlyFields(source, at, "type", "button");
                string name = source["button"] as string;
                if (name != "left" && name != "right" && name != "middle")
                    throw Schema(at + "/button", "must be left, right or middle");
                entry.Source = CHRISMappingSource.MouseButton;
                entry.Button = name;
            }
            else if (vector && type == "key_vector2")
            {
                OnlyFields(source, at, "type", "up", "down", "left", "right");
                entry.Source = CHRISMappingSource.KeyVector2;
                entry.Up = KeyName(source, VectorSides[0], at);
                entry.Down = KeyName(source, VectorSides[1], at);
                entry.Left = KeyName(source, VectorSides[2], at);
                entry.Right = KeyName(source, VectorSides[3], at);
            }
            else if (vector && type == "mouse_delta")
            {
                OnlyFields(source, at, "type");
                entry.Source = CHRISMappingSource.MouseDelta;
            }
            else if (entry.Action == CHRISMappedAction.BrushSize && type == "mouse_wheel")
            {
                OnlyFields(source, at, "type");
                entry.Source = CHRISMappingSource.MouseWheel;
            }
            else throw Schema(at, "no allowed source for this action");
            return entry;
        }

        // RFC 8259 reader that, like the reference, rejects repeated object keys instead of
        // keeping the last one, and accepts NaN/Infinity (they then fail the schema).
        // Objects become Dictionary<string, object>, arrays List<object>, numbers double.
        sealed class StrictJson
        {
            const int MaxDepth = 64;
            readonly string m_Text;
            int m_Pos, m_Depth;

            public StrictJson(string text) { m_Text = text; }

            CHRISMappingException Fail(string detail) =>
                new CHRISMappingException("invalid_json", $"{detail} at character {m_Pos}");

            public object ParseDocument()
            {
                SkipWhitespace();
                object value = ParseValue();
                SkipWhitespace();
                if (m_Pos != m_Text.Length) throw Fail("extra data");
                return value;
            }

            void SkipWhitespace()
            {
                while (m_Pos < m_Text.Length)
                {
                    char c = m_Text[m_Pos];
                    if (c != ' ' && c != '\t' && c != '\n' && c != '\r') return;
                    m_Pos++;
                }
            }

            bool Literal(string word)
            {
                if (string.CompareOrdinal(m_Text, m_Pos, word, 0, word.Length) != 0) return false;
                m_Pos += word.Length;
                return true;
            }

            object ParseValue()
            {
                if (m_Pos >= m_Text.Length) throw Fail("expecting value");
                char c = m_Text[m_Pos];
                if (c == '{' || c == '[')
                {
                    if (++m_Depth > MaxDepth) throw Fail("nesting deeper than " + MaxDepth);
                    object nested = c == '{' ? ParseObject() : (object)ParseArray();
                    m_Depth--;
                    return nested;
                }
                if (c == '"') return ParseString();
                if (Literal("true")) return true;
                if (Literal("false")) return false;
                if (Literal("null")) return null;
                if (Literal("NaN")) return double.NaN;
                if (Literal("Infinity")) return double.PositiveInfinity;
                if (Literal("-Infinity")) return double.NegativeInfinity;
                if (c == '-' || (c >= '0' && c <= '9')) return ParseNumber();
                throw Fail("expecting value");
            }

            Dictionary<string, object> ParseObject()
            {
                var obj = new Dictionary<string, object>(StringComparer.Ordinal);
                m_Pos++;
                SkipWhitespace();
                if (m_Pos < m_Text.Length && m_Text[m_Pos] == '}') { m_Pos++; return obj; }
                while (true)
                {
                    if (m_Pos >= m_Text.Length || m_Text[m_Pos] != '"') throw Fail("expecting property name");
                    string name = ParseString();
                    SkipWhitespace();
                    if (m_Pos >= m_Text.Length || m_Text[m_Pos] != ':') throw Fail("expecting ':'");
                    m_Pos++;
                    SkipWhitespace();
                    object value = ParseValue();
                    if (obj.ContainsKey(name)) throw Fail($"duplicate object key '{name}'");
                    obj[name] = value;
                    SkipWhitespace();
                    if (m_Pos >= m_Text.Length) throw Fail("expecting ',' or '}'");
                    char c = m_Text[m_Pos++];
                    if (c == '}') return obj;
                    if (c != ',') throw Fail("expecting ',' or '}'");
                    SkipWhitespace();
                }
            }

            List<object> ParseArray()
            {
                var list = new List<object>();
                m_Pos++;
                SkipWhitespace();
                if (m_Pos < m_Text.Length && m_Text[m_Pos] == ']') { m_Pos++; return list; }
                while (true)
                {
                    SkipWhitespace();
                    list.Add(ParseValue());
                    SkipWhitespace();
                    if (m_Pos >= m_Text.Length) throw Fail("expecting ',' or ']'");
                    char c = m_Text[m_Pos++];
                    if (c == ']') return list;
                    if (c != ',') throw Fail("expecting ',' or ']'");
                }
            }

            string ParseString()
            {
                var text = new StringBuilder();
                m_Pos++;
                while (true)
                {
                    if (m_Pos >= m_Text.Length) throw Fail("unterminated string");
                    char c = m_Text[m_Pos++];
                    if (c == '"') return text.ToString();
                    if (c < 0x20) throw Fail("control character in string");
                    if (c != '\\') { text.Append(c); continue; }
                    if (m_Pos >= m_Text.Length) throw Fail("unterminated string");
                    switch (m_Text[m_Pos++])
                    {
                        case '"': text.Append('"'); break;
                        case '\\': text.Append('\\'); break;
                        case '/': text.Append('/'); break;
                        case 'b': text.Append('\b'); break;
                        case 'f': text.Append('\f'); break;
                        case 'n': text.Append('\n'); break;
                        case 'r': text.Append('\r'); break;
                        case 't': text.Append('\t'); break;
                        case 'u':
                            if (m_Pos + 4 > m_Text.Length || !ushort.TryParse(m_Text.Substring(m_Pos, 4),
                                    NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture, out var code))
                                throw Fail("invalid \\u escape");
                            text.Append((char)code);
                            m_Pos += 4;
                            break;
                        default: throw Fail("invalid escape");
                    }
                }
            }

            double ParseNumber()
            {
                int start = m_Pos;
                if (m_Text[m_Pos] == '-') m_Pos++;
                if (m_Pos < m_Text.Length && m_Text[m_Pos] == '0') m_Pos++;
                else if (!Digits()) throw Fail("expecting value");
                if (m_Pos < m_Text.Length && m_Text[m_Pos] == '.')
                {
                    m_Pos++;
                    if (!Digits()) throw Fail("invalid number");
                }
                if (m_Pos < m_Text.Length && (m_Text[m_Pos] == 'e' || m_Text[m_Pos] == 'E'))
                {
                    m_Pos++;
                    if (m_Pos < m_Text.Length && (m_Text[m_Pos] == '+' || m_Text[m_Pos] == '-')) m_Pos++;
                    if (!Digits()) throw Fail("invalid number");
                }
                double.TryParse(m_Text.Substring(start, m_Pos - start), NumberStyles.Float,
                    CultureInfo.InvariantCulture, out var number);
                return number;
            }

            bool Digits()
            {
                int start = m_Pos;
                while (m_Pos < m_Text.Length && m_Text[m_Pos] >= '0' && m_Text[m_Pos] <= '9') m_Pos++;
                return m_Pos > start;
            }
        }
    }

    // Holds the mapping in effect. A rejected file leaves the previous mapping (or none) in place.
    public sealed class CHRISInputMappingStore
    {
        public const string RelativePath = "CHRIS/active-mapping.json";

        public CHRISInputMapping Current { get; private set; }
        public byte[] CurrentBytes { get; private set; }
        // "loaded", "missing", "unreadable" or one of the validator codes.
        public string LastResult { get; private set; } = "none";
        public string LastDetail { get; private set; } = "";

        public static string PathUnder(string persistentDataPath) => Path.Combine(persistentDataPath, RelativePath);

        public bool Reload(string path)
        {
            try
            {
                var raw = CHRISInputMapping.ReadBounded(path);
                Current = CHRISInputMapping.Parse(raw);
                CurrentBytes = raw;
                LastResult = "loaded";
                LastDetail = $"{Current.Mappings.Count} mapping(s)";
                return true;
            }
            catch (CHRISMappingException error) { Fail(error.Code, error.Detail); }
            catch (FileNotFoundException) { Fail("missing", path); }
            catch (DirectoryNotFoundException) { Fail("missing", path); }
            catch (IOException error) { Fail("unreadable", error.Message); }
            catch (UnauthorizedAccessException error) { Fail("unreadable", error.Message); }
            return false;
        }

        void Fail(string code, string detail)
        {
            LastResult = code;
            LastDetail = detail;
        }
    }
}
